// auto-generated by quickMigration – 100 制
export const ALL_TEAMS = [
  {
    "id": "NYY",
    "name": "Yankees",
    "batters": [
      {
        "name": "Trent Grisham",
        "pos": "CF",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 60,
          "contact": 50,
          "speed": 80
        }
      },
      {
        "name": "Paul Goldschmidt",
        "pos": "1B",
        "type": "batter",
        "stats": {
          "power": 80,
          "hitRate": 90,
          "contact": 80,
          "speed": 50
        }
      },
      {
        "name": "Aaron Judge",
        "pos": "RF",
        "type": "batter",
        "stats": {
          "power": 100,
          "hitRate": 90,
          "contact": 70,
          "speed": 60
        }
      },
      {
        "name": "Ben Rice",
        "pos": "DH",
        "type": "batter",
        "stats": {
          "power": 80,
          "hitRate": 80,
          "contact": 60,
          "speed": 60
        }
      },
      {
        "name": "Cody Bellinger",
        "pos": "LF",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 60,
          "contact": 60,
          "speed": 70
        }
      },
      {
        "name": "Austin Wells",
        "pos": "C",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 50,
          "contact": 60,
          "speed": 50
        }
      },
      {
        "name": "Anthony Volpe",
        "pos": "SS",
        "type": "batter",
        "stats": {
          "power": 50,
          "hitRate": 70,
          "contact": 70,
          "speed": 90
        }
      },
      {
        "name": "Jazz Chisholm",
        "pos": "2B",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 50,
          "contact": 50,
          "speed": 80
        }
      },
      {
        "name": "Oswaldo Cabrera",
        "pos": "3B",
        "type": "batter",
        "stats": {
          "power": 40,
          "hitRate": 60,
          "contact": 60,
          "speed": 60
        }
      }
    ],
    "pitchers": {
      "startersRotation": [
        {
          "name": "Gerrit Cole",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 100,
            "velocity": 90,
            "control": 70,
            "technique": 80,
            "maxStamina": 1000
          }
        },
        {
          "name": "Max Fried",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 90,
            "velocity": 80,
            "control": 80,
            "technique": 70,
            "maxStamina": 950
          }
        },
        {
          "name": "Carlos Rodón",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 80,
            "velocity": 80,
            "control": 70,
            "technique": 60,
            "maxStamina": 900
          }
        },
        {
          "name": "Clarke Schmidt",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 70,
            "velocity": 80,
            "control": 70,
            "technique": 60,
            "maxStamina": 850
          }
        },
        {
          "name": "Will Warren",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 65,
            "velocity": 60,
            "control": 70,
            "technique": 50,
            "maxStamina": 800
          }
        }
      ],
      "reliever": {
        "name": "Fernando Cruz",
        "type": "pitcher",
        "stats": {
          "role": "Reliever",
          "power": 85,
          "velocity": 65,
          "control": 70,
          "technique": 60,
          "maxStamina": 600
        }
      },
      "closer": {
        "name": "Devin Williams",
        "type": "pitcher",
        "stats": {
          "role": "Closer",
          "power": 80,
          "velocity": 80,
          "control": 50,
          "technique": 70,
          "maxStamina": 500
        }
      }
    }
  },
  {
    "id": "LAD",
    "name": "Dodgers",
    "batters": [
      {
        "name": "Mookie Betts",
        "pos": "SS",
        "type": "batter",
        "stats": {
          "power": 80,
          "hitRate": 80,
          "contact": 80,
          "speed": 90
        }
      },
      {
        "name": "Shohei Ohtani",
        "pos": "DH",
        "type": "batter",
        "stats": {
          "power": 90,
          "hitRate": 90,
          "contact": 80,
          "speed": 80
        }
      },
      {
        "name": "Freddie Freeman",
        "pos": "1B",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 90,
          "contact": 90,
          "speed": 60
        }
      },
      {
        "name": "Teoscar Hernández",
        "pos": "RF",
        "type": "batter",
        "stats": {
          "power": 60,
          "hitRate": 80,
          "contact": 70,
          "speed": 70
        }
      },
      {
        "name": "Will Smith",
        "pos": "C",
        "type": "batter",
        "stats": {
          "power": 60,
          "hitRate": 70,
          "contact": 80,
          "speed": 50
        }
      },
      {
        "name": "Andy Pages",
        "pos": "CF",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 60,
          "contact": 60,
          "speed": 70
        }
      },
      {
        "name": "Tommy Edman",
        "pos": "2B",
        "type": "batter",
        "stats": {
          "power": 60,
          "hitRate": 60,
          "contact": 60,
          "speed": 80
        }
      },
      {
        "name": "Max Muncy",
        "pos": "3B",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 70,
          "contact": 50,
          "speed": 50
        }
      },
      {
        "name": "James Outman",
        "pos": "LF",
        "type": "batter",
        "stats": {
          "power": 70,
          "hitRate": 50,
          "contact": 50,
          "speed": 80
        }
      }
    ],
    "pitchers": {
      "startersRotation": [
        {
          "name": "Yoshinobu Yamamoto",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 80,
            "velocity": 90,
            "control": 90,
            "technique": 80,
            "maxStamina": 950
          }
        },
        {
          "name": "Tyler Glasnow",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 90,
            "velocity": 100,
            "control": 50,
            "technique": 70,
            "maxStamina": 920
          }
        },
        {
          "name": "Walker Buehler",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 80,
            "velocity": 80,
            "control": 80,
            "technique": 80,
            "maxStamina": 960
          }
        },
        {
          "name": "Roki Sasaki",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 80,
            "velocity": 80,
            "control": 60,
            "technique": 70,
            "maxStamina": 850
          }
        },
        {
          "name": "Bobby Miller",
          "type": "pitcher",
          "stats": {
            "role": "Starter",
            "power": 70,
            "velocity": 90,
            "control": 70,
            "technique": 60,
            "maxStamina": 900
          }
        }
      ],
      "reliever": {
        "name": "Blake Treinen",
        "type": "pitcher",
        "stats": {
          "role": "Reliever",
          "power": 70,
          "velocity": 80,
          "control": 70,
          "technique": 60,
          "maxStamina": 700
        }
      },
      "closer": {
        "name": "Evan Phillips",
        "type": "pitcher",
        "stats": {
          "role": "Closer",
          "power": 90,
          "velocity": 90,
          "control": 80,
          "technique": 70,
          "maxStamina": 500
        }
      }
    }
  }
];
export function getTeamById(id){return ALL_TEAMS.find(t=>t.id===id)||null;}
